.TH cdimport 1 "2013-03"
.SH NAME
cdimport \- semi-automatic CD import script

.SH SYNOPSIS

\fBcdimport [-nT] [-d \fIinput\fB] [-e \fIextension\fB] [-F
\fIffmpeg\fB] [-f \fImetapath\fB] [-o \fIoutpath\fB] [@\fImeta-name
value\fB]... [@\fImeta-name\fP=\fIvalue\fB]...\fP

\fBcdimport --help\fP

\fBcdimport --version\fP

.SH DESCRIPTION

\fBcdimport\fP imports a CD or other collected music data into a
central location. Additionally, \fBcdimport\fP sets relevant
metadata. The track title and track number (if present) are set
automatically from the file name (but see the \fB@\fP option for an
exception).

This utility relies on \fBffmpeg\fP(1) to do the conversion. As such,
it must be installed to do anything useful. Coincidentally, this also
means that the wide variety of input formats that ffmpeg understands
are understood by this program.

Summary information is printed to STDERR, and is used as an aid in
double-checking metadata and save location before running. Since some
CDs can take a long time to process, this is a good time to find
mistakes. This summary may be safely discarded.

This script has been written with the opinion that a computer should
store lossless copies of CD audio. Popular disk drives are large and
cheap enough to support this ideal. As such, support for "lossy"
formats like MPEG audio and Vorbis will never be officially
included. If such a need arises, use your favorite conversion utility
to do the translation, or modify the script yourself.

.SS OUTPUT FORMAT

Files are saved using the FLAC format. The naming scheme is as
follows:

.in +2
\fIdisc#\fP.\fItrack#\fP -- \fItitle\fP.flac
.in -2

When there is no disc number, the naming scheme is:

.in +2
\fItrack#\fP -- \fItitle\fP.flac
.in -2

When there is no track number, the naming scheme is:

.in +2
\fItitle\fP.flac
.in -2

.SH OPTIONS

.IP "-d, --dir \fIinput-path\fP"

Use \fIinput-path\fP as the read directory. The default value is
\$PWD.

.IP "-e, --ext \fIextension\fP"

Only read in files with the extension \fIextension\fP. This is useful
when the directory also contains album art.

.IP "-F \fIffmpeg\fP"

Use the given path \fIffmpeg\fP as the location of the ffmpeg
binary. The default value is the lead of \$PATH. If no binary can be
found, or one is found but is invalid, the program will not continue.

.IP "-f \fImeta-path\fP"

Search path for ffmetadata files. Default is to use the input
directory.

See the section FFMETADATA for a quick summary of the basics of this
file.

.IP "-h, --help"

Display this help.

.IP "-n, --dry-run"

Display the ffmpeg commands that the utility would use, but do not
execute them. The commands are printed to STDOUT.

.IP "-o, --outdir \fIoutput-path\fP"

By default, files are saved in "\fIartist\fP/\fIalbum\fP" in the
prefix \$CDIMPORT_DEST. This option overrides that entire path, for
when such behavior is unwanted.

.IP "-T"

By default, \fBcdimport\fP uses the first word of the file name as the
track number. When this behavior is not wanted, \fB\-T\fP turns this
off.

.IP "-v, --version"

Display the program name and version, then exit.

.IP "@\fImeta-name\fP \fIvalue\fP OR @\fImeta-name\fP=\fIvalue\fP"

Option for passing track metadata to ffmpeg. Specify this option as
many times as there is metadata to pass. The second form allows sane
shell expansion.

To pass track-specific metadata, use the form
"\fItrack\fP:\fImeta-name\fP". When 'title' is specified this way (and
\fBONLY\fP this way!), it will override track title from file name
calculation. This form is only meaningful when not using -T.

Declared metadata, embedded metadata, and ffmetadata file metadata
follow the following rules:

.in +2

\fB1.\fP ffmetadata file metadata overrides embedded metadata.

\fB2.\fP Declared metadata overrides ffmetadata file metadata.

\fB3.\fP Declared metadata is unique. Redeclaring metadata clobbers
the previous definition.

\fB4.\fP Track-specific declared metadata overrides non-track-specific
metadata.

\fB5.\fP All metadata keys cannot have an equal sign ("=") in
them. This is a limitation imposed by ffmpeg. Values may have equal
signs.

.in -2

.SH FFMETADATA

There is a supported ffmpeg input format called "ffmetadata" that
stores track metadata similar to an INI file. This file must start
with the line ";FFMETADATA1". Following are lines
"\fIkey\fP=\fIvalue\fP".

.SH ENVIRONMENT

.IP CDIMPORT_DEST

If set and not empty, this is the target prefix of converted
files. The default value is "\$HOME/Music/cdimport".

.SH BUGS

None that I'm aware of!

.SH AUTHOR

Lucien Pullen <drurowin@gmail.com>

.SH "SEE ALSO"

.BR ffmpeg (1)
